# Generated by Django 3.1.14 on 2024-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyectos',
                'ordering': ['-id'],
            },
        ),
    ]
