# Generated by Django 3.1.14 on 2024-10-19 16:36

import random
import base64, hashlib
from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone

def crear_usuario_administrador(apps, schema_editor):
    password = base64.urlsafe_b64encode(hashlib.sha3_512(str(random.random()).encode()).digest())[:20]
    user = User.objects.create_user(
        'hugoruscitti-admin',
        password=password,
        last_login=timezone.now(),
        is_superuser=True,
        is_staff=True
    )
    print(f"Asignando el password inicial: {password}")
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_usuario_administrador, migrations.RunPython.noop),
    ]
