# Generated by Django 3.1.14 on 2024-10-22 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_crear_usuario_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='screenshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='textura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='version',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
